// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :one
UPDATE idempotency_keys
SET
    response_status = $3,
    response_body = $4
WHERE scope = $1
  AND key = $2
RETURNING id, key, scope, request_hash, response_status, response_body, created_at, expires_at
`

type CompleteIdempotencyKeyParams struct {
	Scope          string `json:"scope"`
	Key            string `json:"key"`
	ResponseStatus *int32 `json:"response_status"`
	ResponseBody   []byte `json:"response_body"`
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, completeIdempotencyKey,
		arg.Scope,
		arg.Key,
		arg.ResponseStatus,
		arg.ResponseBody,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Scope,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO idempotency_keys (
    key,
    scope,
    request_hash,
    expires_at
)
VALUES ($1, $2, $3, $4)
RETURNING id, key, scope, request_hash, response_status, response_body, created_at, expires_at
`

type CreateIdempotencyKeyParams struct {
	Key         string             `json:"key"`
	Scope       string             `json:"scope"`
	RequestHash *string            `json:"request_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyKey,
		arg.Key,
		arg.Scope,
		arg.RequestHash,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Scope,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getActiveIdempotencyKey = `-- name: GetActiveIdempotencyKey :one
SELECT id, key, scope, request_hash, response_status, response_body, created_at, expires_at
FROM idempotency_keys
WHERE scope = $1
  AND key = $2
  AND expires_at > now()
`

type GetActiveIdempotencyKeyParams struct {
	Scope string `json:"scope"`
	Key   string `json:"key"`
}

func (q *Queries) GetActiveIdempotencyKey(ctx context.Context, arg GetActiveIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getActiveIdempotencyKey, arg.Scope, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Scope,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
