// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: investments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getInvestmentByID = `-- name: GetInvestmentByID :one
SELECT id, investor_id, principal_cents, annual_rate_bps, term_days, status, currency, simulation_profile, created_at
FROM investments
WHERE id = $1
`

func (q *Queries) GetInvestmentByID(ctx context.Context, id pgtype.UUID) (Investment, error) {
	row := q.db.QueryRow(ctx, getInvestmentByID, id)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.InvestorID,
		&i.PrincipalCents,
		&i.AnnualRateBps,
		&i.TermDays,
		&i.Status,
		&i.Currency,
		&i.SimulationProfile,
		&i.CreatedAt,
	)
	return i, err
}
