// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLedgerAccountByCode = `-- name: GetLedgerAccountByCode :one
SELECT id, code, name, account_type, created_at
FROM ledger_accounts
WHERE code = $1
`

func (q *Queries) GetLedgerAccountByCode(ctx context.Context, code string) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, getLedgerAccountByCode, code)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.AccountType,
		&i.CreatedAt,
	)
	return i, err
}

const getLedgerEntryGroupIDByJobID = `-- name: GetLedgerEntryGroupIDByJobID :one
SELECT entry_group_id
FROM ledger_entries
WHERE settlement_job_id = $1
LIMIT 1
`

func (q *Queries) GetLedgerEntryGroupIDByJobID(ctx context.Context, settlementJobID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getLedgerEntryGroupIDByJobID, settlementJobID)
	var entry_group_id pgtype.UUID
	err := row.Scan(&entry_group_id)
	return entry_group_id, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :one
INSERT INTO ledger_entries (
    entry_group_id,
    settlement_job_id,
    account_id,
    side,
    amount_cents,
    currency,
    description,
    metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, entry_group_id, settlement_job_id, account_id, side, amount_cents, currency, description, posted_at, metadata
`

type InsertLedgerEntryParams struct {
	EntryGroupID    pgtype.UUID `json:"entry_group_id"`
	SettlementJobID pgtype.UUID `json:"settlement_job_id"`
	AccountID       pgtype.UUID `json:"account_id"`
	Side            string      `json:"side"`
	AmountCents     int64       `json:"amount_cents"`
	Currency        string      `json:"currency"`
	Description     string      `json:"description"`
	Metadata        []byte      `json:"metadata"`
}

func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, insertLedgerEntry,
		arg.EntryGroupID,
		arg.SettlementJobID,
		arg.AccountID,
		arg.Side,
		arg.AmountCents,
		arg.Currency,
		arg.Description,
		arg.Metadata,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.EntryGroupID,
		&i.SettlementJobID,
		&i.AccountID,
		&i.Side,
		&i.AmountCents,
		&i.Currency,
		&i.Description,
		&i.PostedAt,
		&i.Metadata,
	)
	return i, err
}

const listLedgerAccounts = `-- name: ListLedgerAccounts :many
SELECT id, code, name, account_type, created_at
FROM ledger_accounts
ORDER BY code ASC
`

func (q *Queries) ListLedgerAccounts(ctx context.Context) ([]LedgerAccount, error) {
	rows, err := q.db.Query(ctx, listLedgerAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerAccount{}
	for rows.Next() {
		var i LedgerAccount
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.AccountType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntries = `-- name: ListLedgerEntries :many
SELECT le.id, le.entry_group_id, le.settlement_job_id, le.account_id, le.side, le.amount_cents, le.currency, le.description, le.posted_at, le.metadata
FROM ledger_entries le
JOIN ledger_accounts la ON la.id = le.account_id
WHERE ($1::uuid IS NULL OR le.settlement_job_id = $1)
  AND ($2::text IS NULL OR la.code = $2)
  AND ($3::timestamptz IS NULL OR le.posted_at >= $3)
  AND ($4::timestamptz IS NULL OR le.posted_at <= $4)
  AND (
    $5::timestamptz IS NULL
    OR le.posted_at < $5
    OR (le.posted_at = $5 AND le.id < $6)
  )
ORDER BY le.posted_at DESC, le.id DESC
LIMIT $7
`

type ListLedgerEntriesParams struct {
	SettlementJobID pgtype.UUID        `json:"settlement_job_id"`
	AccountCode     *string            `json:"account_code"`
	FromTime        pgtype.Timestamptz `json:"from_time"`
	ToTime          pgtype.Timestamptz `json:"to_time"`
	CursorTime      pgtype.Timestamptz `json:"cursor_time"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	LimitVal        int32              `json:"limit_val"`
}

func (q *Queries) ListLedgerEntries(ctx context.Context, arg ListLedgerEntriesParams) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntries,
		arg.SettlementJobID,
		arg.AccountCode,
		arg.FromTime,
		arg.ToTime,
		arg.CursorTime,
		arg.CursorID,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.EntryGroupID,
			&i.SettlementJobID,
			&i.AccountID,
			&i.Side,
			&i.AmountCents,
			&i.Currency,
			&i.Description,
			&i.PostedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntriesByJobID = `-- name: ListLedgerEntriesByJobID :many
SELECT id, entry_group_id, settlement_job_id, account_id, side, amount_cents, currency, description, posted_at, metadata
FROM ledger_entries
WHERE settlement_job_id = $1
ORDER BY posted_at ASC, side DESC
`

func (q *Queries) ListLedgerEntriesByJobID(ctx context.Context, settlementJobID pgtype.UUID) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesByJobID, settlementJobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.EntryGroupID,
			&i.SettlementJobID,
			&i.AccountID,
			&i.Side,
			&i.AmountCents,
			&i.Currency,
			&i.Description,
			&i.PostedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLedgerAccount = `-- name: UpsertLedgerAccount :one
INSERT INTO ledger_accounts (code, name, account_type)
VALUES ($1, $2, $3)
ON CONFLICT (code) DO UPDATE
SET name = EXCLUDED.name
RETURNING id, code, name, account_type, created_at
`

type UpsertLedgerAccountParams struct {
	Code        string `json:"code"`
	Name        string `json:"name"`
	AccountType string `json:"account_type"`
}

func (q *Queries) UpsertLedgerAccount(ctx context.Context, arg UpsertLedgerAccountParams) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, upsertLedgerAccount, arg.Code, arg.Name, arg.AccountType)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.AccountType,
		&i.CreatedAt,
	)
	return i, err
}
