// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maturity.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMaturityScheduleByID = `-- name: GetMaturityScheduleByID :one
SELECT id, investment_id, matures_at, status, settled_at, created_at
FROM maturity_schedules
WHERE id = $1
`

func (q *Queries) GetMaturityScheduleByID(ctx context.Context, id pgtype.UUID) (MaturitySchedule, error) {
	row := q.db.QueryRow(ctx, getMaturityScheduleByID, id)
	var i MaturitySchedule
	err := row.Scan(
		&i.ID,
		&i.InvestmentID,
		&i.MaturesAt,
		&i.Status,
		&i.SettledAt,
		&i.CreatedAt,
	)
	return i, err
}

const listDueMaturitySchedules = `-- name: ListDueMaturitySchedules :many
SELECT
    m.id, m.investment_id, m.matures_at, m.status, m.settled_at, m.created_at,
    i.id, i.investor_id, i.principal_cents, i.annual_rate_bps, i.term_days, i.status, i.currency, i.simulation_profile, i.created_at
FROM maturity_schedules m
INNER JOIN investments i ON i.id = m.investment_id
WHERE m.status = 'pending'
  AND m.matures_at <= now()
ORDER BY m.matures_at ASC
FOR UPDATE OF m SKIP LOCKED
`

type ListDueMaturitySchedulesRow struct {
	MaturitySchedule MaturitySchedule `json:"maturity_schedule"`
	Investment       Investment       `json:"investment"`
}

// Scheduler scan: pending maturities at or past due date.
// FOR UPDATE SKIP LOCKED prevents duplicate enqueue under concurrent schedulers.
func (q *Queries) ListDueMaturitySchedules(ctx context.Context) ([]ListDueMaturitySchedulesRow, error) {
	rows, err := q.db.Query(ctx, listDueMaturitySchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueMaturitySchedulesRow{}
	for rows.Next() {
		var i ListDueMaturitySchedulesRow
		if err := rows.Scan(
			&i.MaturitySchedule.ID,
			&i.MaturitySchedule.InvestmentID,
			&i.MaturitySchedule.MaturesAt,
			&i.MaturitySchedule.Status,
			&i.MaturitySchedule.SettledAt,
			&i.MaturitySchedule.CreatedAt,
			&i.Investment.ID,
			&i.Investment.InvestorID,
			&i.Investment.PrincipalCents,
			&i.Investment.AnnualRateBps,
			&i.Investment.TermDays,
			&i.Investment.Status,
			&i.Investment.Currency,
			&i.Investment.SimulationProfile,
			&i.Investment.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMaturitySettled = `-- name: MarkMaturitySettled :one
UPDATE maturity_schedules
SET
    status = 'settled',
    settled_at = now()
WHERE id = $1
  AND status IN ('pending', 'processing')
RETURNING id, investment_id, matures_at, status, settled_at, created_at
`

func (q *Queries) MarkMaturitySettled(ctx context.Context, id pgtype.UUID) (MaturitySchedule, error) {
	row := q.db.QueryRow(ctx, markMaturitySettled, id)
	var i MaturitySchedule
	err := row.Scan(
		&i.ID,
		&i.InvestmentID,
		&i.MaturesAt,
		&i.Status,
		&i.SettledAt,
		&i.CreatedAt,
	)
	return i, err
}
