// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditActorType string

const (
	AuditActorTypeSystem AuditActorType = "system"
	AuditActorTypeAdmin  AuditActorType = "admin"
	AuditActorTypeApi    AuditActorType = "api"
)

func (e *AuditActorType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditActorType(s)
	case string:
		*e = AuditActorType(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditActorType: %T", src)
	}
	return nil
}

type NullAuditActorType struct {
	AuditActorType AuditActorType `json:"audit_actor_type"`
	Valid          bool           `json:"valid"` // Valid is true if AuditActorType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditActorType) Scan(value interface{}) error {
	if value == nil {
		ns.AuditActorType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditActorType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditActorType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditActorType), nil
}

type ErrorClass string

const (
	ErrorClassTransient ErrorClass = "transient"
	ErrorClassTerminal  ErrorClass = "terminal"
)

func (e *ErrorClass) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ErrorClass(s)
	case string:
		*e = ErrorClass(s)
	default:
		return fmt.Errorf("unsupported scan type for ErrorClass: %T", src)
	}
	return nil
}

type NullErrorClass struct {
	ErrorClass ErrorClass `json:"error_class"`
	Valid      bool       `json:"valid"` // Valid is true if ErrorClass is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullErrorClass) Scan(value interface{}) error {
	if value == nil {
		ns.ErrorClass, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ErrorClass.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullErrorClass) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ErrorClass), nil
}

type InvestmentStatus string

const (
	InvestmentStatusActive    InvestmentStatus = "active"
	InvestmentStatusMatured   InvestmentStatus = "matured"
	InvestmentStatusSettled   InvestmentStatus = "settled"
	InvestmentStatusCancelled InvestmentStatus = "cancelled"
)

func (e *InvestmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvestmentStatus(s)
	case string:
		*e = InvestmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvestmentStatus: %T", src)
	}
	return nil
}

type NullInvestmentStatus struct {
	InvestmentStatus InvestmentStatus `json:"investment_status"`
	Valid            bool             `json:"valid"` // Valid is true if InvestmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvestmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvestmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvestmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvestmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvestmentStatus), nil
}

type MaturityStatus string

const (
	MaturityStatusPending    MaturityStatus = "pending"
	MaturityStatusProcessing MaturityStatus = "processing"
	MaturityStatusSettled    MaturityStatus = "settled"
	MaturityStatusSkipped    MaturityStatus = "skipped"
)

func (e *MaturityStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MaturityStatus(s)
	case string:
		*e = MaturityStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MaturityStatus: %T", src)
	}
	return nil
}

type NullMaturityStatus struct {
	MaturityStatus MaturityStatus `json:"maturity_status"`
	Valid          bool           `json:"valid"` // Valid is true if MaturityStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMaturityStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MaturityStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MaturityStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMaturityStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MaturityStatus), nil
}

type PayoutAttemptStatus string

const (
	PayoutAttemptStatusStarted   PayoutAttemptStatus = "started"
	PayoutAttemptStatusSucceeded PayoutAttemptStatus = "succeeded"
	PayoutAttemptStatusFailed    PayoutAttemptStatus = "failed"
)

func (e *PayoutAttemptStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PayoutAttemptStatus(s)
	case string:
		*e = PayoutAttemptStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PayoutAttemptStatus: %T", src)
	}
	return nil
}

type NullPayoutAttemptStatus struct {
	PayoutAttemptStatus PayoutAttemptStatus `json:"payout_attempt_status"`
	Valid               bool                `json:"valid"` // Valid is true if PayoutAttemptStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPayoutAttemptStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PayoutAttemptStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PayoutAttemptStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPayoutAttemptStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PayoutAttemptStatus), nil
}

type SettlementJobStatus string

const (
	SettlementJobStatusPending    SettlementJobStatus = "pending"
	SettlementJobStatusProcessing SettlementJobStatus = "processing"
	SettlementJobStatusSucceeded  SettlementJobStatus = "succeeded"
	SettlementJobStatusFailed     SettlementJobStatus = "failed"
	SettlementJobStatusDeadLetter SettlementJobStatus = "dead_letter"
)

func (e *SettlementJobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SettlementJobStatus(s)
	case string:
		*e = SettlementJobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SettlementJobStatus: %T", src)
	}
	return nil
}

type NullSettlementJobStatus struct {
	SettlementJobStatus SettlementJobStatus `json:"settlement_job_status"`
	Valid               bool                `json:"valid"` // Valid is true if SettlementJobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSettlementJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SettlementJobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SettlementJobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSettlementJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SettlementJobStatus), nil
}

type AuditEvent struct {
	ID            pgtype.UUID        `json:"id"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	ActorType     AuditActorType     `json:"actor_type"`
	ActorID       string             `json:"actor_id"`
	Action        string             `json:"action"`
	EntityType    string             `json:"entity_type"`
	EntityID      pgtype.UUID        `json:"entity_id"`
	Payload       []byte             `json:"payload"`
	CorrelationID string             `json:"correlation_id"`
}

type IdempotencyKey struct {
	ID             pgtype.UUID        `json:"id"`
	Key            string             `json:"key"`
	Scope          string             `json:"scope"`
	RequestHash    *string            `json:"request_hash"`
	ResponseStatus *int32             `json:"response_status"`
	ResponseBody   []byte             `json:"response_body"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

type Investment struct {
	ID                pgtype.UUID        `json:"id"`
	InvestorID        pgtype.UUID        `json:"investor_id"`
	PrincipalCents    int64              `json:"principal_cents"`
	AnnualRateBps     int32              `json:"annual_rate_bps"`
	TermDays          int32              `json:"term_days"`
	Status            InvestmentStatus   `json:"status"`
	Currency          string             `json:"currency"`
	SimulationProfile *string            `json:"simulation_profile"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Investor struct {
	ID          pgtype.UUID        `json:"id"`
	ExternalRef string             `json:"external_ref"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type LedgerAccount struct {
	ID          pgtype.UUID        `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	AccountType string             `json:"account_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type LedgerEntry struct {
	ID              pgtype.UUID        `json:"id"`
	EntryGroupID    pgtype.UUID        `json:"entry_group_id"`
	SettlementJobID pgtype.UUID        `json:"settlement_job_id"`
	AccountID       pgtype.UUID        `json:"account_id"`
	Side            string             `json:"side"`
	AmountCents     int64              `json:"amount_cents"`
	Currency        string             `json:"currency"`
	Description     string             `json:"description"`
	PostedAt        pgtype.Timestamptz `json:"posted_at"`
	Metadata        []byte             `json:"metadata"`
}

type MaturitySchedule struct {
	ID           pgtype.UUID        `json:"id"`
	InvestmentID pgtype.UUID        `json:"investment_id"`
	MaturesAt    pgtype.Timestamptz `json:"matures_at"`
	Status       MaturityStatus     `json:"status"`
	SettledAt    pgtype.Timestamptz `json:"settled_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type PayoutAttempt struct {
	ID              pgtype.UUID         `json:"id"`
	SettlementJobID pgtype.UUID         `json:"settlement_job_id"`
	AttemptNumber   int32               `json:"attempt_number"`
	Status          PayoutAttemptStatus `json:"status"`
	PayoutReference *string             `json:"payout_reference"`
	ErrorMessage    *string             `json:"error_message"`
	ErrorClass      *ErrorClass         `json:"error_class"`
	StartedAt       pgtype.Timestamptz  `json:"started_at"`
	FinishedAt      pgtype.Timestamptz  `json:"finished_at"`
}

type ReconciliationSnapshot struct {
	ID                  pgtype.UUID        `json:"id"`
	SnapshotAt          pgtype.Timestamptz `json:"snapshot_at"`
	ExpectedJobCount    int32              `json:"expected_job_count"`
	ExpectedTotalCents  int64              `json:"expected_total_cents"`
	SucceededCount      int32              `json:"succeeded_count"`
	SucceededTotalCents int64              `json:"succeeded_total_cents"`
	PendingCount        int32              `json:"pending_count"`
	FailedCount         int32              `json:"failed_count"`
	DeadLetterCount     int32              `json:"dead_letter_count"`
	DiscrepancyCents    int64              `json:"discrepancy_cents"`
	Details             []byte             `json:"details"`
}

type SettlementJob struct {
	ID                  pgtype.UUID         `json:"id"`
	MaturityScheduleID  pgtype.UUID         `json:"maturity_schedule_id"`
	InvestmentID        pgtype.UUID         `json:"investment_id"`
	IdempotencyKey      string              `json:"idempotency_key"`
	Status              SettlementJobStatus `json:"status"`
	PrincipalCents      int64               `json:"principal_cents"`
	GrossReturnCents    int64               `json:"gross_return_cents"`
	PlatformFeeCents    int64               `json:"platform_fee_cents"`
	WithholdingTaxCents int64               `json:"withholding_tax_cents"`
	NetPayoutCents      int64               `json:"net_payout_cents"`
	PayoutReference     *string             `json:"payout_reference"`
	RetryCount          int32               `json:"retry_count"`
	MaxRetries          int32               `json:"max_retries"`
	NextRetryAt         pgtype.Timestamptz  `json:"next_retry_at"`
	ProcessingStartedAt pgtype.Timestamptz  `json:"processing_started_at"`
	ProcessingOwner     *string             `json:"processing_owner"`
	LastError           *string             `json:"last_error"`
	ErrorClass          *ErrorClass         `json:"error_class"`
	DeadLetterReason    *string             `json:"dead_letter_reason"`
	CreatedAt           pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz  `json:"updated_at"`
	CompletedAt         pgtype.Timestamptz  `json:"completed_at"`
}
