// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payout_attempts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayoutAttempt = `-- name: CreatePayoutAttempt :one
INSERT INTO payout_attempts (
    settlement_job_id,
    attempt_number,
    status
)
VALUES ($1, $2, 'started')
RETURNING id, settlement_job_id, attempt_number, status, payout_reference, error_message, error_class, started_at, finished_at
`

type CreatePayoutAttemptParams struct {
	SettlementJobID pgtype.UUID `json:"settlement_job_id"`
	AttemptNumber   int32       `json:"attempt_number"`
}

func (q *Queries) CreatePayoutAttempt(ctx context.Context, arg CreatePayoutAttemptParams) (PayoutAttempt, error) {
	row := q.db.QueryRow(ctx, createPayoutAttempt, arg.SettlementJobID, arg.AttemptNumber)
	var i PayoutAttempt
	err := row.Scan(
		&i.ID,
		&i.SettlementJobID,
		&i.AttemptNumber,
		&i.Status,
		&i.PayoutReference,
		&i.ErrorMessage,
		&i.ErrorClass,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishPayoutAttemptFailure = `-- name: FinishPayoutAttemptFailure :one
UPDATE payout_attempts
SET
    status = 'failed',
    error_message = $2,
    error_class = $3,
    finished_at = now()
WHERE id = $1
  AND status = 'started'
RETURNING id, settlement_job_id, attempt_number, status, payout_reference, error_message, error_class, started_at, finished_at
`

type FinishPayoutAttemptFailureParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage *string     `json:"error_message"`
	ErrorClass   *ErrorClass `json:"error_class"`
}

func (q *Queries) FinishPayoutAttemptFailure(ctx context.Context, arg FinishPayoutAttemptFailureParams) (PayoutAttempt, error) {
	row := q.db.QueryRow(ctx, finishPayoutAttemptFailure, arg.ID, arg.ErrorMessage, arg.ErrorClass)
	var i PayoutAttempt
	err := row.Scan(
		&i.ID,
		&i.SettlementJobID,
		&i.AttemptNumber,
		&i.Status,
		&i.PayoutReference,
		&i.ErrorMessage,
		&i.ErrorClass,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishPayoutAttemptSuccess = `-- name: FinishPayoutAttemptSuccess :one
UPDATE payout_attempts
SET
    status = 'succeeded',
    payout_reference = $2,
    finished_at = now()
WHERE id = $1
  AND status = 'started'
RETURNING id, settlement_job_id, attempt_number, status, payout_reference, error_message, error_class, started_at, finished_at
`

type FinishPayoutAttemptSuccessParams struct {
	ID              pgtype.UUID `json:"id"`
	PayoutReference *string     `json:"payout_reference"`
}

func (q *Queries) FinishPayoutAttemptSuccess(ctx context.Context, arg FinishPayoutAttemptSuccessParams) (PayoutAttempt, error) {
	row := q.db.QueryRow(ctx, finishPayoutAttemptSuccess, arg.ID, arg.PayoutReference)
	var i PayoutAttempt
	err := row.Scan(
		&i.ID,
		&i.SettlementJobID,
		&i.AttemptNumber,
		&i.Status,
		&i.PayoutReference,
		&i.ErrorMessage,
		&i.ErrorClass,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getNextAttemptNumber = `-- name: GetNextAttemptNumber :one
SELECT COALESCE(MAX(attempt_number), 0) + 1 AS next_attempt_number
FROM payout_attempts
WHERE settlement_job_id = $1
`

func (q *Queries) GetNextAttemptNumber(ctx context.Context, settlementJobID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getNextAttemptNumber, settlementJobID)
	var next_attempt_number int32
	err := row.Scan(&next_attempt_number)
	return next_attempt_number, err
}

const listPayoutAttemptsByJobID = `-- name: ListPayoutAttemptsByJobID :many
SELECT id, settlement_job_id, attempt_number, status, payout_reference, error_message, error_class, started_at, finished_at
FROM payout_attempts
WHERE settlement_job_id = $1
ORDER BY attempt_number ASC
`

func (q *Queries) ListPayoutAttemptsByJobID(ctx context.Context, settlementJobID pgtype.UUID) ([]PayoutAttempt, error) {
	rows, err := q.db.Query(ctx, listPayoutAttemptsByJobID, settlementJobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PayoutAttempt{}
	for rows.Next() {
		var i PayoutAttempt
		if err := rows.Scan(
			&i.ID,
			&i.SettlementJobID,
			&i.AttemptNumber,
			&i.Status,
			&i.PayoutReference,
			&i.ErrorMessage,
			&i.ErrorClass,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
