// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reconciliation.sql

package sqlc

import (
	"context"
)

const aggregateSettlementJobStats = `-- name: AggregateSettlementJobStats :one
SELECT
    COUNT(*)::int AS total_job_count,
    COUNT(*) FILTER (WHERE status = 'pending')::int AS pending_count,
    COUNT(*) FILTER (WHERE status = 'processing')::int AS processing_count,
    COUNT(*) FILTER (WHERE status = 'failed')::int AS failed_count,
    COUNT(*) FILTER (WHERE status = 'dead_letter')::int AS dead_letter_count,
    COUNT(*) FILTER (WHERE status = 'succeeded')::int AS succeeded_count,
    COALESCE(SUM(net_payout_cents), 0)::bigint AS expected_total_cents,
    COALESCE(SUM(net_payout_cents) FILTER (WHERE status = 'succeeded'), 0)::bigint AS succeeded_total_cents
FROM settlement_jobs
`

type AggregateSettlementJobStatsRow struct {
	TotalJobCount       int32 `json:"total_job_count"`
	PendingCount        int32 `json:"pending_count"`
	ProcessingCount     int32 `json:"processing_count"`
	FailedCount         int32 `json:"failed_count"`
	DeadLetterCount     int32 `json:"dead_letter_count"`
	SucceededCount      int32 `json:"succeeded_count"`
	ExpectedTotalCents  int64 `json:"expected_total_cents"`
	SucceededTotalCents int64 `json:"succeeded_total_cents"`
}

func (q *Queries) AggregateSettlementJobStats(ctx context.Context) (AggregateSettlementJobStatsRow, error) {
	row := q.db.QueryRow(ctx, aggregateSettlementJobStats)
	var i AggregateSettlementJobStatsRow
	err := row.Scan(
		&i.TotalJobCount,
		&i.PendingCount,
		&i.ProcessingCount,
		&i.FailedCount,
		&i.DeadLetterCount,
		&i.SucceededCount,
		&i.ExpectedTotalCents,
		&i.SucceededTotalCents,
	)
	return i, err
}

const createReconciliationSnapshot = `-- name: CreateReconciliationSnapshot :one
INSERT INTO reconciliation_snapshots (
    expected_job_count,
    expected_total_cents,
    succeeded_count,
    succeeded_total_cents,
    pending_count,
    failed_count,
    dead_letter_count,
    discrepancy_cents,
    details
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, snapshot_at, expected_job_count, expected_total_cents, succeeded_count, succeeded_total_cents, pending_count, failed_count, dead_letter_count, discrepancy_cents, details
`

type CreateReconciliationSnapshotParams struct {
	ExpectedJobCount    int32  `json:"expected_job_count"`
	ExpectedTotalCents  int64  `json:"expected_total_cents"`
	SucceededCount      int32  `json:"succeeded_count"`
	SucceededTotalCents int64  `json:"succeeded_total_cents"`
	PendingCount        int32  `json:"pending_count"`
	FailedCount         int32  `json:"failed_count"`
	DeadLetterCount     int32  `json:"dead_letter_count"`
	DiscrepancyCents    int64  `json:"discrepancy_cents"`
	Details             []byte `json:"details"`
}

func (q *Queries) CreateReconciliationSnapshot(ctx context.Context, arg CreateReconciliationSnapshotParams) (ReconciliationSnapshot, error) {
	row := q.db.QueryRow(ctx, createReconciliationSnapshot,
		arg.ExpectedJobCount,
		arg.ExpectedTotalCents,
		arg.SucceededCount,
		arg.SucceededTotalCents,
		arg.PendingCount,
		arg.FailedCount,
		arg.DeadLetterCount,
		arg.DiscrepancyCents,
		arg.Details,
	)
	var i ReconciliationSnapshot
	err := row.Scan(
		&i.ID,
		&i.SnapshotAt,
		&i.ExpectedJobCount,
		&i.ExpectedTotalCents,
		&i.SucceededCount,
		&i.SucceededTotalCents,
		&i.PendingCount,
		&i.FailedCount,
		&i.DeadLetterCount,
		&i.DiscrepancyCents,
		&i.Details,
	)
	return i, err
}

const getLatestReconciliationSnapshot = `-- name: GetLatestReconciliationSnapshot :one
SELECT id, snapshot_at, expected_job_count, expected_total_cents, succeeded_count, succeeded_total_cents, pending_count, failed_count, dead_letter_count, discrepancy_cents, details
FROM reconciliation_snapshots
ORDER BY snapshot_at DESC
LIMIT 1
`

func (q *Queries) GetLatestReconciliationSnapshot(ctx context.Context) (ReconciliationSnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestReconciliationSnapshot)
	var i ReconciliationSnapshot
	err := row.Scan(
		&i.ID,
		&i.SnapshotAt,
		&i.ExpectedJobCount,
		&i.ExpectedTotalCents,
		&i.SucceededCount,
		&i.SucceededTotalCents,
		&i.PendingCount,
		&i.FailedCount,
		&i.DeadLetterCount,
		&i.DiscrepancyCents,
		&i.Details,
	)
	return i, err
}
