// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reconciliation.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateSettlementJobStats = `-- name: AggregateSettlementJobStats :one
SELECT
    COUNT(*)::int AS total_job_count,
    COUNT(*) FILTER (WHERE status = 'pending')::int AS pending_count,
    COUNT(*) FILTER (WHERE status = 'processing')::int AS processing_count,
    COUNT(*) FILTER (WHERE status = 'failed')::int AS failed_count,
    COUNT(*) FILTER (WHERE status = 'dead_letter')::int AS dead_letter_count,
    COUNT(*) FILTER (WHERE status = 'succeeded')::int AS succeeded_count,
    COALESCE(SUM(net_payout_cents), 0)::bigint AS expected_total_cents,
    COALESCE(SUM(net_payout_cents) FILTER (WHERE status = 'succeeded'), 0)::bigint AS succeeded_total_cents
FROM settlement_jobs
`

type AggregateSettlementJobStatsRow struct {
	TotalJobCount       int32 `json:"total_job_count"`
	PendingCount        int32 `json:"pending_count"`
	ProcessingCount     int32 `json:"processing_count"`
	FailedCount         int32 `json:"failed_count"`
	DeadLetterCount     int32 `json:"dead_letter_count"`
	SucceededCount      int32 `json:"succeeded_count"`
	ExpectedTotalCents  int64 `json:"expected_total_cents"`
	SucceededTotalCents int64 `json:"succeeded_total_cents"`
}

func (q *Queries) AggregateSettlementJobStats(ctx context.Context) (AggregateSettlementJobStatsRow, error) {
	row := q.db.QueryRow(ctx, aggregateSettlementJobStats)
	var i AggregateSettlementJobStatsRow
	err := row.Scan(
		&i.TotalJobCount,
		&i.PendingCount,
		&i.ProcessingCount,
		&i.FailedCount,
		&i.DeadLetterCount,
		&i.SucceededCount,
		&i.ExpectedTotalCents,
		&i.SucceededTotalCents,
	)
	return i, err
}

const countOrphanLedgerJobGroups = `-- name: CountOrphanLedgerJobGroups :one
SELECT COUNT(*)::int AS count
FROM (
    SELECT DISTINCT le.settlement_job_id
    FROM ledger_entries le
    WHERE NOT EXISTS (
        SELECT 1
        FROM settlement_jobs j
        WHERE j.id = le.settlement_job_id
          AND j.status = 'succeeded'
    )
) orphan_groups
`

func (q *Queries) CountOrphanLedgerJobGroups(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countOrphanLedgerJobGroups)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countStalePendingJobs = `-- name: CountStalePendingJobs :one
SELECT COUNT(*)::int AS count
FROM settlement_jobs
WHERE status = 'pending'
  AND created_at < (now() - interval '1 hour')
`

func (q *Queries) CountStalePendingJobs(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countStalePendingJobs)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countSucceededJobsWithoutLedger = `-- name: CountSucceededJobsWithoutLedger :one
SELECT COUNT(*)::int AS count
FROM settlement_jobs j
WHERE j.status = 'succeeded'
  AND NOT EXISTS (
    SELECT 1 FROM ledger_entries le WHERE le.settlement_job_id = j.id
  )
`

func (q *Queries) CountSucceededJobsWithoutLedger(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countSucceededJobsWithoutLedger)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createReconciliationSnapshot = `-- name: CreateReconciliationSnapshot :one
INSERT INTO reconciliation_snapshots (
    expected_job_count,
    expected_total_cents,
    succeeded_count,
    succeeded_total_cents,
    pending_count,
    failed_count,
    dead_letter_count,
    discrepancy_cents,
    details
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, snapshot_at, expected_job_count, expected_total_cents, succeeded_count, succeeded_total_cents, pending_count, failed_count, dead_letter_count, discrepancy_cents, details
`

type CreateReconciliationSnapshotParams struct {
	ExpectedJobCount    int32  `json:"expected_job_count"`
	ExpectedTotalCents  int64  `json:"expected_total_cents"`
	SucceededCount      int32  `json:"succeeded_count"`
	SucceededTotalCents int64  `json:"succeeded_total_cents"`
	PendingCount        int32  `json:"pending_count"`
	FailedCount         int32  `json:"failed_count"`
	DeadLetterCount     int32  `json:"dead_letter_count"`
	DiscrepancyCents    int64  `json:"discrepancy_cents"`
	Details             []byte `json:"details"`
}

func (q *Queries) CreateReconciliationSnapshot(ctx context.Context, arg CreateReconciliationSnapshotParams) (ReconciliationSnapshot, error) {
	row := q.db.QueryRow(ctx, createReconciliationSnapshot,
		arg.ExpectedJobCount,
		arg.ExpectedTotalCents,
		arg.SucceededCount,
		arg.SucceededTotalCents,
		arg.PendingCount,
		arg.FailedCount,
		arg.DeadLetterCount,
		arg.DiscrepancyCents,
		arg.Details,
	)
	var i ReconciliationSnapshot
	err := row.Scan(
		&i.ID,
		&i.SnapshotAt,
		&i.ExpectedJobCount,
		&i.ExpectedTotalCents,
		&i.SucceededCount,
		&i.SucceededTotalCents,
		&i.PendingCount,
		&i.FailedCount,
		&i.DeadLetterCount,
		&i.DiscrepancyCents,
		&i.Details,
	)
	return i, err
}

const getLatestReconciliationSnapshot = `-- name: GetLatestReconciliationSnapshot :one
SELECT id, snapshot_at, expected_job_count, expected_total_cents, succeeded_count, succeeded_total_cents, pending_count, failed_count, dead_letter_count, discrepancy_cents, details
FROM reconciliation_snapshots
ORDER BY snapshot_at DESC
LIMIT 1
`

func (q *Queries) GetLatestReconciliationSnapshot(ctx context.Context) (ReconciliationSnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestReconciliationSnapshot)
	var i ReconciliationSnapshot
	err := row.Scan(
		&i.ID,
		&i.SnapshotAt,
		&i.ExpectedJobCount,
		&i.ExpectedTotalCents,
		&i.SucceededCount,
		&i.SucceededTotalCents,
		&i.PendingCount,
		&i.FailedCount,
		&i.DeadLetterCount,
		&i.DiscrepancyCents,
		&i.Details,
	)
	return i, err
}

const listReconciliationSnapshots = `-- name: ListReconciliationSnapshots :many
SELECT id, snapshot_at, expected_job_count, expected_total_cents, succeeded_count, succeeded_total_cents, pending_count, failed_count, dead_letter_count, discrepancy_cents, details
FROM reconciliation_snapshots
WHERE (
    $1::timestamptz IS NULL
    OR snapshot_at < $1
    OR (snapshot_at = $1 AND id < $2)
)
ORDER BY snapshot_at DESC, id DESC
LIMIT $3
`

type ListReconciliationSnapshotsParams struct {
	CursorTime pgtype.Timestamptz `json:"cursor_time"`
	CursorID   pgtype.UUID        `json:"cursor_id"`
	LimitVal   int32              `json:"limit_val"`
}

func (q *Queries) ListReconciliationSnapshots(ctx context.Context, arg ListReconciliationSnapshotsParams) ([]ReconciliationSnapshot, error) {
	rows, err := q.db.Query(ctx, listReconciliationSnapshots, arg.CursorTime, arg.CursorID, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconciliationSnapshot{}
	for rows.Next() {
		var i ReconciliationSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotAt,
			&i.ExpectedJobCount,
			&i.ExpectedTotalCents,
			&i.SucceededCount,
			&i.SucceededTotalCents,
			&i.PendingCount,
			&i.FailedCount,
			&i.DeadLetterCount,
			&i.DiscrepancyCents,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
