// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settlement_jobs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimSettlementJob = `-- name: ClaimSettlementJob :one
WITH candidate AS (
    SELECT id
    FROM settlement_jobs
    WHERE status IN ('pending', 'failed')
      AND (next_retry_at IS NULL OR next_retry_at <= now())
    ORDER BY next_retry_at ASC NULLS FIRST, created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE settlement_jobs j
SET
    status = 'processing',
    processing_started_at = now(),
    processing_owner = $1,
    updated_at = now()
FROM candidate c
WHERE j.id = c.id
RETURNING j.id, j.maturity_schedule_id, j.investment_id, j.idempotency_key, j.status, j.principal_cents, j.gross_return_cents, j.platform_fee_cents, j.withholding_tax_cents, j.net_payout_cents, j.payout_reference, j.retry_count, j.max_retries, j.next_retry_at, j.processing_started_at, j.processing_owner, j.last_error, j.error_class, j.dead_letter_reason, j.created_at, j.updated_at, j.completed_at
`

// Atomically selects and leases the next claimable job for a worker.
func (q *Queries) ClaimSettlementJob(ctx context.Context, processingOwner *string) (SettlementJob, error) {
	row := q.db.QueryRow(ctx, claimSettlementJob, processingOwner)
	var i SettlementJob
	err := row.Scan(
		&i.ID,
		&i.MaturityScheduleID,
		&i.InvestmentID,
		&i.IdempotencyKey,
		&i.Status,
		&i.PrincipalCents,
		&i.GrossReturnCents,
		&i.PlatformFeeCents,
		&i.WithholdingTaxCents,
		&i.NetPayoutCents,
		&i.PayoutReference,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.ProcessingStartedAt,
		&i.ProcessingOwner,
		&i.LastError,
		&i.ErrorClass,
		&i.DeadLetterReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createSettlementJob = `-- name: CreateSettlementJob :one
INSERT INTO settlement_jobs (
    maturity_schedule_id,
    investment_id,
    idempotency_key,
    status,
    principal_cents,
    gross_return_cents,
    platform_fee_cents,
    withholding_tax_cents,
    net_payout_cents,
    max_retries
)
VALUES (
    $1, $2, $3, 'pending',
    $4, $5, $6, $7, $8, $9
)
RETURNING id, maturity_schedule_id, investment_id, idempotency_key, status, principal_cents, gross_return_cents, platform_fee_cents, withholding_tax_cents, net_payout_cents, payout_reference, retry_count, max_retries, next_retry_at, processing_started_at, processing_owner, last_error, error_class, dead_letter_reason, created_at, updated_at, completed_at
`

type CreateSettlementJobParams struct {
	MaturityScheduleID  pgtype.UUID `json:"maturity_schedule_id"`
	InvestmentID        pgtype.UUID `json:"investment_id"`
	IdempotencyKey      string      `json:"idempotency_key"`
	PrincipalCents      int64       `json:"principal_cents"`
	GrossReturnCents    int64       `json:"gross_return_cents"`
	PlatformFeeCents    int64       `json:"platform_fee_cents"`
	WithholdingTaxCents int64       `json:"withholding_tax_cents"`
	NetPayoutCents      int64       `json:"net_payout_cents"`
	MaxRetries          int32       `json:"max_retries"`
}

func (q *Queries) CreateSettlementJob(ctx context.Context, arg CreateSettlementJobParams) (SettlementJob, error) {
	row := q.db.QueryRow(ctx, createSettlementJob,
		arg.MaturityScheduleID,
		arg.InvestmentID,
		arg.IdempotencyKey,
		arg.PrincipalCents,
		arg.GrossReturnCents,
		arg.PlatformFeeCents,
		arg.WithholdingTaxCents,
		arg.NetPayoutCents,
		arg.MaxRetries,
	)
	var i SettlementJob
	err := row.Scan(
		&i.ID,
		&i.MaturityScheduleID,
		&i.InvestmentID,
		&i.IdempotencyKey,
		&i.Status,
		&i.PrincipalCents,
		&i.GrossReturnCents,
		&i.PlatformFeeCents,
		&i.WithholdingTaxCents,
		&i.NetPayoutCents,
		&i.PayoutReference,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.ProcessingStartedAt,
		&i.ProcessingOwner,
		&i.LastError,
		&i.ErrorClass,
		&i.DeadLetterReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const expireStaleProcessingJobs = `-- name: ExpireStaleProcessingJobs :many
UPDATE settlement_jobs
SET
    status = 'pending',
    processing_started_at = NULL,
    processing_owner = NULL,
    updated_at = now()
WHERE status = 'processing'
  AND processing_started_at < $1
RETURNING id, maturity_schedule_id, investment_id, idempotency_key, status, principal_cents, gross_return_cents, platform_fee_cents, withholding_tax_cents, net_payout_cents, payout_reference, retry_count, max_retries, next_retry_at, processing_started_at, processing_owner, last_error, error_class, dead_letter_reason, created_at, updated_at, completed_at
`

func (q *Queries) ExpireStaleProcessingJobs(ctx context.Context, processingStartedAt pgtype.Timestamptz) ([]SettlementJob, error) {
	rows, err := q.db.Query(ctx, expireStaleProcessingJobs, processingStartedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SettlementJob{}
	for rows.Next() {
		var i SettlementJob
		if err := rows.Scan(
			&i.ID,
			&i.MaturityScheduleID,
			&i.InvestmentID,
			&i.IdempotencyKey,
			&i.Status,
			&i.PrincipalCents,
			&i.GrossReturnCents,
			&i.PlatformFeeCents,
			&i.WithholdingTaxCents,
			&i.NetPayoutCents,
			&i.PayoutReference,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.ProcessingStartedAt,
			&i.ProcessingOwner,
			&i.LastError,
			&i.ErrorClass,
			&i.DeadLetterReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSettlementJobByID = `-- name: GetSettlementJobByID :one
SELECT id, maturity_schedule_id, investment_id, idempotency_key, status, principal_cents, gross_return_cents, platform_fee_cents, withholding_tax_cents, net_payout_cents, payout_reference, retry_count, max_retries, next_retry_at, processing_started_at, processing_owner, last_error, error_class, dead_letter_reason, created_at, updated_at, completed_at
FROM settlement_jobs
WHERE id = $1
`

func (q *Queries) GetSettlementJobByID(ctx context.Context, id pgtype.UUID) (SettlementJob, error) {
	row := q.db.QueryRow(ctx, getSettlementJobByID, id)
	var i SettlementJob
	err := row.Scan(
		&i.ID,
		&i.MaturityScheduleID,
		&i.InvestmentID,
		&i.IdempotencyKey,
		&i.Status,
		&i.PrincipalCents,
		&i.GrossReturnCents,
		&i.PlatformFeeCents,
		&i.WithholdingTaxCents,
		&i.NetPayoutCents,
		&i.PayoutReference,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.ProcessingStartedAt,
		&i.ProcessingOwner,
		&i.LastError,
		&i.ErrorClass,
		&i.DeadLetterReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getSettlementJobByMaturityScheduleID = `-- name: GetSettlementJobByMaturityScheduleID :one
SELECT id, maturity_schedule_id, investment_id, idempotency_key, status, principal_cents, gross_return_cents, platform_fee_cents, withholding_tax_cents, net_payout_cents, payout_reference, retry_count, max_retries, next_retry_at, processing_started_at, processing_owner, last_error, error_class, dead_letter_reason, created_at, updated_at, completed_at
FROM settlement_jobs
WHERE maturity_schedule_id = $1
`

func (q *Queries) GetSettlementJobByMaturityScheduleID(ctx context.Context, maturityScheduleID pgtype.UUID) (SettlementJob, error) {
	row := q.db.QueryRow(ctx, getSettlementJobByMaturityScheduleID, maturityScheduleID)
	var i SettlementJob
	err := row.Scan(
		&i.ID,
		&i.MaturityScheduleID,
		&i.InvestmentID,
		&i.IdempotencyKey,
		&i.Status,
		&i.PrincipalCents,
		&i.GrossReturnCents,
		&i.PlatformFeeCents,
		&i.WithholdingTaxCents,
		&i.NetPayoutCents,
		&i.PayoutReference,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.ProcessingStartedAt,
		&i.ProcessingOwner,
		&i.LastError,
		&i.ErrorClass,
		&i.DeadLetterReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listSettlementJobs = `-- name: ListSettlementJobs :many
SELECT id, maturity_schedule_id, investment_id, idempotency_key, status, principal_cents, gross_return_cents, platform_fee_cents, withholding_tax_cents, net_payout_cents, payout_reference, retry_count, max_retries, next_retry_at, processing_started_at, processing_owner, last_error, error_class, dead_letter_reason, created_at, updated_at, completed_at
FROM settlement_jobs
WHERE ($1::settlement_job_status IS NULL OR status = $1)
  AND ($2::uuid IS NULL OR investment_id = $2)
  AND (
    $3::timestamptz IS NULL
    OR created_at < $3
    OR (created_at = $3 AND id < $4)
  )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListSettlementJobsParams struct {
	Status       *SettlementJobStatus `json:"status"`
	InvestmentID pgtype.UUID          `json:"investment_id"`
	CursorTime   pgtype.Timestamptz   `json:"cursor_time"`
	CursorID     pgtype.UUID          `json:"cursor_id"`
	LimitVal     int32                `json:"limit_val"`
}

func (q *Queries) ListSettlementJobs(ctx context.Context, arg ListSettlementJobsParams) ([]SettlementJob, error) {
	rows, err := q.db.Query(ctx, listSettlementJobs,
		arg.Status,
		arg.InvestmentID,
		arg.CursorTime,
		arg.CursorID,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SettlementJob{}
	for rows.Next() {
		var i SettlementJob
		if err := rows.Scan(
			&i.ID,
			&i.MaturityScheduleID,
			&i.InvestmentID,
			&i.IdempotencyKey,
			&i.Status,
			&i.PrincipalCents,
			&i.GrossReturnCents,
			&i.PlatformFeeCents,
			&i.WithholdingTaxCents,
			&i.NetPayoutCents,
			&i.PayoutReference,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.ProcessingStartedAt,
			&i.ProcessingOwner,
			&i.LastError,
			&i.ErrorClass,
			&i.DeadLetterReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobDeadLetter = `-- name: MarkJobDeadLetter :one
UPDATE settlement_jobs
SET
    status = 'dead_letter',
    dead_letter_reason = $2,
    last_error = $3,
    error_class = $4,
    processing_started_at = NULL,
    processing_owner = NULL,
    updated_at = now()
WHERE id = $1
  AND status = 'processing'
RETURNING id, maturity_schedule_id, investment_id, idempotency_key, status, principal_cents, gross_return_cents, platform_fee_cents, withholding_tax_cents, net_payout_cents, payout_reference, retry_count, max_retries, next_retry_at, processing_started_at, processing_owner, last_error, error_class, dead_letter_reason, created_at, updated_at, completed_at
`

type MarkJobDeadLetterParams struct {
	ID               pgtype.UUID `json:"id"`
	DeadLetterReason *string     `json:"dead_letter_reason"`
	LastError        *string     `json:"last_error"`
	ErrorClass       *ErrorClass `json:"error_class"`
}

func (q *Queries) MarkJobDeadLetter(ctx context.Context, arg MarkJobDeadLetterParams) (SettlementJob, error) {
	row := q.db.QueryRow(ctx, markJobDeadLetter,
		arg.ID,
		arg.DeadLetterReason,
		arg.LastError,
		arg.ErrorClass,
	)
	var i SettlementJob
	err := row.Scan(
		&i.ID,
		&i.MaturityScheduleID,
		&i.InvestmentID,
		&i.IdempotencyKey,
		&i.Status,
		&i.PrincipalCents,
		&i.GrossReturnCents,
		&i.PlatformFeeCents,
		&i.WithholdingTaxCents,
		&i.NetPayoutCents,
		&i.PayoutReference,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.ProcessingStartedAt,
		&i.ProcessingOwner,
		&i.LastError,
		&i.ErrorClass,
		&i.DeadLetterReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const markJobFailedRetryable = `-- name: MarkJobFailedRetryable :one
UPDATE settlement_jobs
SET
    status = 'failed',
    retry_count = retry_count + 1,
    next_retry_at = $2,
    last_error = $3,
    error_class = 'transient',
    processing_started_at = NULL,
    processing_owner = NULL,
    updated_at = now()
WHERE id = $1
  AND status = 'processing'
RETURNING id, maturity_schedule_id, investment_id, idempotency_key, status, principal_cents, gross_return_cents, platform_fee_cents, withholding_tax_cents, net_payout_cents, payout_reference, retry_count, max_retries, next_retry_at, processing_started_at, processing_owner, last_error, error_class, dead_letter_reason, created_at, updated_at, completed_at
`

type MarkJobFailedRetryableParams struct {
	ID          pgtype.UUID        `json:"id"`
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
	LastError   *string            `json:"last_error"`
}

func (q *Queries) MarkJobFailedRetryable(ctx context.Context, arg MarkJobFailedRetryableParams) (SettlementJob, error) {
	row := q.db.QueryRow(ctx, markJobFailedRetryable, arg.ID, arg.NextRetryAt, arg.LastError)
	var i SettlementJob
	err := row.Scan(
		&i.ID,
		&i.MaturityScheduleID,
		&i.InvestmentID,
		&i.IdempotencyKey,
		&i.Status,
		&i.PrincipalCents,
		&i.GrossReturnCents,
		&i.PlatformFeeCents,
		&i.WithholdingTaxCents,
		&i.NetPayoutCents,
		&i.PayoutReference,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.ProcessingStartedAt,
		&i.ProcessingOwner,
		&i.LastError,
		&i.ErrorClass,
		&i.DeadLetterReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const markJobSucceeded = `-- name: MarkJobSucceeded :one
UPDATE settlement_jobs
SET
    status = 'succeeded',
    payout_reference = $2,
    completed_at = now(),
    processing_started_at = NULL,
    processing_owner = NULL,
    last_error = NULL,
    error_class = NULL,
    updated_at = now()
WHERE id = $1
  AND status = 'processing'
RETURNING id, maturity_schedule_id, investment_id, idempotency_key, status, principal_cents, gross_return_cents, platform_fee_cents, withholding_tax_cents, net_payout_cents, payout_reference, retry_count, max_retries, next_retry_at, processing_started_at, processing_owner, last_error, error_class, dead_letter_reason, created_at, updated_at, completed_at
`

type MarkJobSucceededParams struct {
	ID              pgtype.UUID `json:"id"`
	PayoutReference *string     `json:"payout_reference"`
}

func (q *Queries) MarkJobSucceeded(ctx context.Context, arg MarkJobSucceededParams) (SettlementJob, error) {
	row := q.db.QueryRow(ctx, markJobSucceeded, arg.ID, arg.PayoutReference)
	var i SettlementJob
	err := row.Scan(
		&i.ID,
		&i.MaturityScheduleID,
		&i.InvestmentID,
		&i.IdempotencyKey,
		&i.Status,
		&i.PrincipalCents,
		&i.GrossReturnCents,
		&i.PlatformFeeCents,
		&i.WithholdingTaxCents,
		&i.NetPayoutCents,
		&i.PayoutReference,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.ProcessingStartedAt,
		&i.ProcessingOwner,
		&i.LastError,
		&i.ErrorClass,
		&i.DeadLetterReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const replayDeadLetterJob = `-- name: ReplayDeadLetterJob :one
UPDATE settlement_jobs
SET
    status = 'pending',
    dead_letter_reason = NULL,
    last_error = NULL,
    error_class = NULL,
    next_retry_at = NULL,
    processing_started_at = NULL,
    processing_owner = NULL,
    updated_at = now()
WHERE id = $1
  AND status = 'dead_letter'
RETURNING id, maturity_schedule_id, investment_id, idempotency_key, status, principal_cents, gross_return_cents, platform_fee_cents, withholding_tax_cents, net_payout_cents, payout_reference, retry_count, max_retries, next_retry_at, processing_started_at, processing_owner, last_error, error_class, dead_letter_reason, created_at, updated_at, completed_at
`

func (q *Queries) ReplayDeadLetterJob(ctx context.Context, id pgtype.UUID) (SettlementJob, error) {
	row := q.db.QueryRow(ctx, replayDeadLetterJob, id)
	var i SettlementJob
	err := row.Scan(
		&i.ID,
		&i.MaturityScheduleID,
		&i.InvestmentID,
		&i.IdempotencyKey,
		&i.Status,
		&i.PrincipalCents,
		&i.GrossReturnCents,
		&i.PlatformFeeCents,
		&i.WithholdingTaxCents,
		&i.NetPayoutCents,
		&i.PayoutReference,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.ProcessingStartedAt,
		&i.ProcessingOwner,
		&i.LastError,
		&i.ErrorClass,
		&i.DeadLetterReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const requeueFailedJob = `-- name: RequeueFailedJob :one
UPDATE settlement_jobs
SET
    status = 'pending',
    next_retry_at = NULL,
    processing_started_at = NULL,
    processing_owner = NULL,
    updated_at = now()
WHERE id = $1
  AND status = 'failed'
RETURNING id, maturity_schedule_id, investment_id, idempotency_key, status, principal_cents, gross_return_cents, platform_fee_cents, withholding_tax_cents, net_payout_cents, payout_reference, retry_count, max_retries, next_retry_at, processing_started_at, processing_owner, last_error, error_class, dead_letter_reason, created_at, updated_at, completed_at
`

func (q *Queries) RequeueFailedJob(ctx context.Context, id pgtype.UUID) (SettlementJob, error) {
	row := q.db.QueryRow(ctx, requeueFailedJob, id)
	var i SettlementJob
	err := row.Scan(
		&i.ID,
		&i.MaturityScheduleID,
		&i.InvestmentID,
		&i.IdempotencyKey,
		&i.Status,
		&i.PrincipalCents,
		&i.GrossReturnCents,
		&i.PlatformFeeCents,
		&i.WithholdingTaxCents,
		&i.NetPayoutCents,
		&i.PayoutReference,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.ProcessingStartedAt,
		&i.ProcessingOwner,
		&i.LastError,
		&i.ErrorClass,
		&i.DeadLetterReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
